Conecto\FeratelDsi\Dtos\OfferRequestSettingsType\ServiceProviderAType:
    properties:
        id:
            expose: true
            access_type: public_method
            serialized_name: Id
            accessor:
                getter: getId
                setter: setId
            xml_attribute: true
            type: string
        product:
            expose: true
            access_type: public_method
            serialized_name: Product
            xml_element:
                cdata: false
                namespace: 'http://interface.deskline.net/DSI/XSD'
            accessor:
                getter: getProduct
                setter: setProduct
            type: Conecto\FeratelDsi\Dtos\OfferRequestSettingsType\ServiceProviderAType\ProductAType
